### ISSUE TITLE
AYSlidingPickerView is not moved to back

### ISSUE THREAD

**Issue by phuna** [yenbekbay/AYSlidingPickerView#2]
Hi,
My use case is quite simple:
I have 2 view controllers let say A, B (A is in a navigation controller). Flow is:
- From A I tap a button to display B to create a new data record.
- From B I tap another button to dismiss B and add that record to A's property (`NSMutableArray*`).
- In A's `viewWillAppear` I check if number of records > 0 then I add them to AYSlidingPickerView

The problem is: 
- If I display B using `[A.navigationController pushViewController:animated:]` then AYSlidingPickerView works normally.
- If I display B using `[A presentViewController:animated:completion:]` then when B is dismissed the AYSlidingPickerView will be displayed above A so I can not do anything with A anymore.

My fix:
For now to fix it I put AYSlidingPickerView to back again in `[A viewDidAppear:]` as shown in code below but I feel like a hack so I hope you can take a look and suggest a better fix.

Code of A:

``` objectivec
#import "ViewController.h"
#import "ItemViewController.h"
#import <AYSlidingPickerView/AYSlidingPickerView.h>

@interface ViewController () {
    NSMutableArray *texts;
    AYSlidingPickerView *pickerView;
}

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    texts = [[NSMutableArray alloc] init];
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];

    if ([texts count] > 0) {
        pickerView = [AYSlidingPickerView sharedInstance];

        NSMutableArray *items = [[NSMutableArray alloc] initWithCapacity:[texts count]];
        for (NSString *s in texts) {
            AYSlidingPickerViewItem *item = [[AYSlidingPickerViewItem alloc] initWithTitle:s handler:^(BOOL completed) {
                self.navigationController.title = s;
            }];
            [items addObject:item];
        }
        pickerView.mainView = self.view;
        pickerView.items = items;
        pickerView.selectedIndex = 0;
        pickerView.closeOnSelection = YES;
        [pickerView addGestureRecognizersToNavigationBar:self.navigationController.navigationBar];
    }

}

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];

    // To ensure picker view is sent to back
   [[UIApplication sharedApplication].delegate.window sendSubviewToBack:pickerView];
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    [pickerView removeGestureRecognizersFromNavigationBar:self.navigationController.navigationBar];
}

- (IBAction)addItem:(id)sender {
    ItemViewController *ivc = [self.storyboard instantiateViewControllerWithIdentifier:@"ItemViewController"];
    ivc.texts = texts;
    [self presentViewController:ivc animated:YES completion:nil];
//    [self.navigationController pushViewController:ivc animated:YES];

}
```

Code of B:

``` objectivec
#import "ItemViewController.h"

@interface ItemViewController ()
@property (weak, nonatomic) IBOutlet UITextField *textToAdd;

@end

@implementation ItemViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
  NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
  [formatter setDateStyle:NSDateFormatterFullStyle];

  self.textToAdd.text = [formatter stringFromDate:[NSDate date]];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}
- (IBAction)addItemTapped:(id)sender {
  [self.texts addObject:self.textToAdd.text];
  [self dismissViewControllerAnimated:YES completion:nil];
//    [self.navigationController popViewControllerAnimated:YES];
}

@end
```

**Comment by yenbekbay** [comment]
@phuna I just tried to reproduce your scenario and I don't seem to have the problem that you described. Can you share your project with me so I can have a better look?

**Comment by phuna** [comment]
@yenbekbay : The sample project is here: https://github.com/phuna/sliding-picker-problem-demo
Is run with Xcode 7.2.1 (7C1002) on OSX 10.11.3

**Comment by yenbekbay** [comment]
@phuna Thank you.

The issue is simple. In your case the picker view is not created until the `texts` array has at least one element, which is after the view is presented.

To fix it, you can move this whole part

``` objc
pickerView = [AYSlidingPickerView sharedInstance];
pickerView.mainView = self.view;
pickerView.closeOnSelection = YES;
```

to `viewDidLoad`. This is also more favorable because setting properties of picker view each time the view is presented is redundant.

Another thing: you don't need to use `sharedInstance` if you only use the picker view in one view controller.

**Comment by phuna** [comment]
@yenbekbay Thank you, move initialization part to `viewDidLoad` solves my problem :)
